### PR TITLE
Add logo

### LINKED ISSUE #4: Logo ideas
Hi and welcome to nodeschool!

If you have any designers you can make a logo https://github.com/nodeschool/nodeschool.github.io/tree/master/images/make-a-sticker

Maybe the Gyeongbokgung Palace or the Namsan Tower can be used as inspiration for the logo?

### PR DESCRIPTION
**Pull request by ghost**
close #4

### CODE REVIEW

**Comment by marocchino** [comment]
Thanks! :bow:

**Comment by finnp** [comment]
Wow, what an awesome sticker! :ok_woman:

**Comment by finnp** [comment]
You should totally PR this to the hexdex: http://nodeschool.io/hexdex

**Comment by marocchino** [comment]
Added. :smile:  [9ff0674](https://github.com/nodeschool/nodeschool.github.io/commit/9ff0674622143fdfdb4f62c84c4f2b1d2ad557a9)

**Comment by sudodoki** [comment]
:+1: Looks great!

**Comment by outsideris** [comment]
Awesome!!! :100:

**Comment by hibiyasleep** [comment]
Very Awesome :+1:

**Comment by ghost** [comment]
Thank you :)

**Pull request merged**
